version: '2'
services:
  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - dnsdock
  dnsdock:
    image: aacebedo/dnsdock:latest-amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
